# -*- coding: utf-8 -*-
"""Pratical-NLP-with-Tranformers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yv1aN1UAmyNcF01ssGgbBBknPfMxxyS5

# Installing Transformers
"""

!pip install -q transformers

from transformers import pipeline

"""# Sentiment Analysis"""

classifier = pipeline("sentiment-analysis")

text = "It's great to learn NLP for me"
classifier(text)

import pandas as pd
outputs = classifier(text)
pd.DataFrame(outputs)

"""# Zero-Shot Classification"""

classifier = pipeline("zero-shot-classification")

text = "This is a tutorial about Hugging Face"
labels = ["tech", "education", "business"]
outputs = classifier(text, labels)
pd.DataFrame(outputs)

"""# Text Generation"""

generator = pipeline("text-generation")

prompt= "This tutorial will walk you through how to"
outputs = generator(prompt)
print(outputs)

outputs = generator(prompt, max_length=50)
print(outputs[0]["generated_text"])

"""## Text generation with distilgpt2"""

generator = pipeline("text-generation", model="distilgpt2")

outputs = generator(prompt, max_length=50)
print(outputs[0]["generated_text"])

"""# Named Entity Recognition (NER)"""

ner = pipeline("ner", grouped_entities=True)

text = "My name is Tirendaz from Turkey. HuggingFace is a nice platform"
outputs = ner(text)
pd.DataFrame(outputs)

"""# Question-Answering"""

reader = pipeline("question-answering")

text = "My name is Tirendaz and I love Berlin"
quenstion = "Where do I like"
outputs = reader(question=quenstion, context=text)
pd.DataFrame([outputs])

"""# Summarization"""

summarizer = pipeline("summarization")

text = """James Stephen Donaldson[b] (born May 7, 1998), known professionally as MrBeast (or Jimmy Donaldson), is an American YouTuber, entrepreneur and philanthropist. He is credited with pioneering a genre of YouTube videos that centers on expensive stunts and challenges.[12] With over 184 million subscribers as of September 18, 2023,[13] he is the most-subscribed individual user on the platform and the second-most-subscribed channel overall,[14][15] and has ranked on the Forbes list for the highest paid YouTube creator in 2022.[16]

Donaldson grew up in Greenville, North Carolina. He began posting videos to YouTube in early 2012, at the age of 13,[17] under the handle MrBeast6000. His early content ranged from Let's Plays to "videos estimating the wealth of other YouTubers".[18] He went viral in 2017 after his "counting to 100,000" video earned tens of thousands of views in just a few days, and he has become increasingly popular ever since, with most of his videos gaining tens of millions of views.[18] His videos, typically involving challenges and giveaways, became increasingly grand and extravagant.[19] Once his channel took off, Donaldson hired some of his childhood friends to co-run the brand. As of 2023, the MrBeast team is made up of over 250 people, including Donaldson himself.[20][21] Other than MrBeast, Donaldson runs the YouTube channels Beast Reacts, MrBeast Gaming, MrBeast 2 (formerly MrBeast Shorts),[22] and the philanthropy channel Beast Philanthropy.[23][24] He formerly ran MrBeast 3 (initially MrBeast 2), which is now inactive.[25][26] As of 2023, he is the highest paid YouTuber,[27] and has an estimated net worth of $500 million.[28]

Donaldson is the founder of MrBeast Burger and Feastables; and a co-creator of Team Trees, a fundraiser for the Arbor Day Foundation that has raised over $23 million;[29][30] and Team Seas, a fundraiser for Ocean Conservancy and The Ocean Cleanup that has raised over $30 million.[31] Donaldson won the Creator of the Year award four times at the Streamy Awards in 2020, 2021, 2022, and 2023; he also won the Favorite Male Creator award twice at the Nickelodeon Kids' Choice Awards in 2022 and 2023. In 2023, Time magazine named him as one of the world's 100 most influential people. """

outputs = summarizer(text, max_length=60, clean_up_tokenization_spaces = True)
print(outputs[0]["summary_text"])

"""# Translation"""

translator = pipeline("translation_en_to_de")

text = "I hope you enjoy it"
outputs = translator(text, clean_up_tokenization_spaces = True)
print(outputs[0]["translation_text"])

"""Let's connect [YouTube](http://youtube.com/tirendazacademy) | [Medium](http://tirendazacademy.medium.com) | [Twitter](http://twitter.com/tirendazacademy) | [Instagram](https://www.instagram.com/tirendazacademy) | [GitHub](http://github.com/tirendazacademy) | [Linkedin](https://www.linkedin.com/in/tirendaz-academy) | [Kaggle](https://www.kaggle.com/tirendazacademy) 😎"""