# -*- coding: utf-8 -*-
"""Working-with-Transformers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OR4K0Us1lo-YYdcziROtAvjiBQ5QkO6I

# Transformers Installing
"""

!pip install -q transformers

"""# Initializing Pipeline"""

from transformers import pipeline

speech_recognizer = pipeline("automatic-speech-recognition")

"""# Installing Dataset"""

!pip install -q datasets

from datasets import load_dataset

dataset = load_dataset("PolyAI/minds14", name="en-US", split="train")

dataset.features

"""# Data Preprocessing"""

from datasets import Audio

dataset = dataset.cast_column("audio", Audio(sampling_rate=speech_recognizer.feature_extractor.sampling_rate))

"""# Speech Recognition"""

result = speech_recognizer(dataset[:4]["audio"])
print([d["text"] for d in result])

"""# Use a Model in the Pipeline"""

from transformers import AutoModelForSequenceClassification

model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
model = AutoModelForSequenceClassification.from_pretrained(model_name)

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(model_name)
classifier = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

"""# Prediction"""

classifier("C'est un film génial. J'aime ça.")

"""# AutoTokenizer"""

encoding = tokenizer("This film is nice. I liked it.")
print(encoding)

batch = tokenizer(
    ["I like NLP. This is an awosome area", "We hope you don't hate it."],
    max_length=512,
	  truncation=True,
    padding=True,
    return_tensors="pt") # Tensorflow kullanılacaksa tf olarak girilmeli

batch

"""# AutoModel"""

model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
model = AutoModelForSequenceClassification.from_pretrained(model_name)

outputs = model(**batch)

from torch import nn

predictions = nn.functional.softmax(outputs.logits, dim=-1)
print(predictions)

"""# Saving the Model"""

save_directory = "./save_pretrained"
tokenizer.save_pretrained(save_directory)
model.save_pretrained(save_directory)

"""Let's connect [YouTube](http://youtube.com/tirendazacademy) | [Medium](http://tirendazacademy.medium.com) | [Twitter](http://twitter.com/tirendazacademy) | [Instagram](https://www.instagram.com/tirendazacademy) | [GitHub](http://github.com/tirendazacademy) | [Linkedin](https://www.linkedin.com/in/tirendaz-academy) | [Kaggle](https://www.kaggle.com/tirendazacademy) 😎"""